version: '3.8'
services:
  api:
    build: .
    container_name: api
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
