version: '3.8'
services:
  nest-app:
    build: .
    container_name: nest-app
    restart: always
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
